const checkoutFormData = [
  { type: "sectionHeading", label: "BILLING DETAILS", id: "0" },
  {
    name: "name",
    type: "text",
    label: "Name",
    id: "1",
    placeholder: "John Doe",
    alwaysRequired: true,
    validationPattern: "[a-zA-Zà-üÀ-Ü\\s]+",
    invalidText: "Only characters",
  },
  {
    name: "email",
    type: "email",
    label: "Email Address",
    id: "2",
    placeholder: "test@example.us",
    alwaysRequired: true,
    validationPattern: "[a-zà-ü0-9._%+\\-]+@[a-zà-ü0-9.\\-]+\\.[a-z]{2,}",
    invalidText: "Wrong format",
  },
  {
    name: "tel",
    type: "tel",
    label: "Phone Number",
    id: "3",
    placeholder: "(+)16019521325",
    alwaysRequired: false,
    validationPattern: "\\+?[0-9\\s]+",
    invalidText: "Only numbers/+",
  },
  { type: "sectionHeading", label: "SHIPPING INFO", id: "4" },
  {
    name: "address",
    type: "text",
    label: "Your Address",
    id: "5",
    placeholder: "1600 Fake Street",
    alwaysRequired: true,
    extraSpace: true,
  },
  {
    name: "zip",
    type: "text",
    label: "ZIP Code",
    id: "6",
    placeholder: "94043",
    alwaysRequired: true,
    validationPattern: "[0-9]{5}",
    invalidText: "Only 5-digits",
  },
  {
    name: "city",
    type: "text",
    label: "City",
    id: "7",
    placeholder: "Mountain View",
    alwaysRequired: true,
    validationPattern: "[a-zà-üA-ZÀ-Ü\\-\\.\\s]+",
    invalidText: "Only characters",
  },
  {
    name: "country",
    type: "text",
    label: "Counry",
    id: "8",
    placeholder: "United States",
    alwaysRequired: true,
    validationPattern: "[a-zà-üA-ZÀ-Ü\\-\\.\\s]+",
    invalidText: "Only characters",
  },
  { type: "sectionHeading", label: "PAYMENT DETAILS", id: "9" },
  {
    name: "paymentMethod",
    type: "radio",
    label: "e-Money",
    id: "10",
    value: "e-Money",
    placeholder: "",
    alwaysRequired: false,
    checked: true,
  },
  {
    name: "paymentMethod",
    type: "radio",
    label: "Cash on Delivery",
    id: "11",
    value: "cash",
    placeholder: "",
    alwaysRequired: false,
    checked: false,
  },
  {
    name: "eMoneyNum",
    type: "text",
    label: "e-Money-Number",
    id: "12",
    placeholder: "12938723",
    alwaysRequired: false,
    validationPattern: "[0-9]{8}",
    invalidText: "Only 8-digits",
    conditionalRender: true,
  },
  {
    name: "eMoneyPin",
    type: "text",
    label: "e-Money-Pin",
    id: "13",
    placeholder: "38471823",
    alwaysRequired: false,
    validationPattern: "[0-9]{8}",
    invalidText: "Only 8-digits",
    conditionalRender: true,
  },
];

export default checkoutFormData;
