const checkoutFormData = [
  { type: "sectionHeading", label: "BILLING DETAILS", id: "0" },
  {
    name: "name",
    type: "text",
    label: "Name",
    id: "1",
    placeholder: "John Doe",
    alwaysRequired: true,
  },
  {
    name: "email",
    type: "email",
    label: "Email Address",
    id: "2",
    placeholder: "test@example.us",
    alwaysRequired: true,
  },
  {
    name: "tel",
    type: "tel",
    label: "Phone Number",
    id: "3",
    placeholder: "16019521325",
    alwaysRequired: false,
  },
  { type: "sectionHeading", label: "SHIPPING INFO", id: "4" },
  {
    name: "address",
    type: "text",
    label: "Your Address",
    id: "5",
    placeholder: "1600 Fake Street",
    alwaysRequired: true,
    extraSpace: true,
  },
  {
    name: "zip",
    type: "number",
    label: "ZIP Code",
    id: "6",
    placeholder: "94043",
    alwaysRequired: true,
  },
  {
    name: "city",
    type: "text",
    label: "City",
    id: "7",
    placeholder: "Mountain View",
    alwaysRequired: true,
  },
  {
    name: "country",
    type: "text",
    label: "Counry",
    id: "8",
    placeholder: "United States",
    alwaysRequired: true,
  },
  { type: "sectionHeading", label: "PAYMENT DETAILS", id: "9" },
  {
    name: "paymentMethod",
    type: "radio",
    label: "e-Money",
    id: "10",
    placeholder: "",
    alwaysRequired: false,
    checked: true,
  },
  {
    name: "paymentMethod",
    type: "radio",
    label: "Cash on Delivery",
    id: "11",
    placeholder: "",
    alwaysRequired: false,
    checked: false,
  },
  {
    name: "eMoneyNum",
    type: "number",
    label: "e-Money-Number",
    id: "12",
    placeholder: "12938723",
    condtionallyRequired: true,
  },
  {
    name: "eMoneyPin",
    type: "number",
    label: "e-Money-Pin",
    id: "13",
    placeholder: "38471823",
    condtionallyRequired: true,
  },
];

export default checkoutFormData;
